import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { CHANGED_FILES_GATE_PATH, DEFAULT_COVERAGE_THRESHOLD } from "../domain/gates.js";

/**
 * The changed-files gate, run by check steps as `node .code-factory/gates/changed-files-gate.mjs
 * <lint|types|coverage>` and by agents with `--base <commit>`. It detects the project's own tools
 * (ESLint, TypeScript, Jest or Vitest in node_modules/.bin) and reports a gate as not applicable
 * when the tool is missing, so a template loop works in any project. Plain JavaScript without
 * template literals, kept as a string so the same file ships in the package and in development.
 */
const GATE_SCRIPT = String.raw`#!/usr/bin/env node
// Generated by Code Factory; rewritten when it differs. Edit the source in Code Factory instead.
// Usage: node .code-factory/gates/changed-files-gate.mjs <lint|types|coverage> [--base <commit>]
// Exit codes: 0 pass or not applicable, 1 gate failed, 2 usage or setup error.
import { spawnSync } from "node:child_process"
import { existsSync, mkdtempSync, readFileSync, realpathSync, rmSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"

const THRESHOLD = Number(process.env.CODE_FACTORY_COVERAGE_THRESHOLD || "${DEFAULT_COVERAGE_THRESHOLD}")
const root = process.cwd()
const bin = name => join(root, "node_modules", ".bin", name)
const has = name => existsSync(bin(name))
const run = (command, args) => spawnSync(command, args, { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 })
const print = result => {
  if (result.stdout) process.stdout.write(result.stdout)
  if (result.stderr) process.stderr.write(result.stderr)
  if (result.error) console.log("Could not start: " + result.error.message)
}
const done = (code, message) => {
  console.log(message)
  process.exit(code)
}

const baseFlag = process.argv.indexOf("--base")
const base = baseFlag > 0 ? process.argv[baseFlag + 1] : undefined
// Check steps receive the list from Code Factory; an agent passes --base and Git derives it.
const listFromGit = revision => {
  const git = args => spawnSync("git", args, { cwd: root, encoding: "utf8" }).stdout || ""
  const scope = ["--", ".", ":(exclude).code-factory"]
  return git(["diff", "--name-only", "--no-renames", "--diff-filter=d", revision, ...scope]) +
    git(["ls-files", "--others", "--exclude-standard", ...scope])
}
const listed = process.env.CODE_FACTORY_CHANGED_FILES ?? (base ? listFromGit(base) : undefined)

const CODE = /\.(c|m)?(js|jsx|ts|tsx)$/
const TEST = /(__tests__\/|\.(test|spec)\.(c|m)?(js|jsx|ts|tsx)$)/
// Sources without unit coverage expectations: declarations, stories, mocks, configs, browser tests.
const NOT_UNIT_SOURCE = /(\.d\.ts$|\.stories\.|__mocks__\/|__fixtures__\/|(^|\/)[^/]*\.config\.|(^|\/)(e2e|playwright|cypress)\/)/

const lint = changed => {
  const files = changed.filter(path => CODE.test(path))
  if (!files.length) done(0, "No changed JS/TS files to lint.")
  if (!has("eslint")) done(0, "ESLint is not installed in this project; lint gate not applicable.")
  console.log("Linting " + files.length + " changed file(s):\n" + files.join("\n"))
  const result = run(bin("eslint"), ["--quiet", "--", ...files])
  print(result)
  done(result.status === 0 ? 0 : 1, result.status === 0 ? "Lint passed for changed files." : "Lint failed for changed files.")
}

// Types are project-wide, so tsc checks the whole program and the gate fails only on errors
// located in changed files, reporting how many errors exist elsewhere.
const types = changed => {
  const files = new Set(changed.filter(path => /\.(c|m)?tsx?$/.test(path)))
  if (!files.size) done(0, "No changed TypeScript files to type-check.")
  if (!has("tsc") || !existsSync(join(root, "tsconfig.json")))
    done(0, "TypeScript (tsc and tsconfig.json) is not set up in this project; type gate not applicable.")
  const result = run(bin("tsc"), ["--noEmit", "--pretty", "false"])
  if (result.status === 0) done(0, "Type check passed (" + files.size + " changed file(s) included).")
  const errors = (result.stdout + result.stderr).split("\n").filter(line => /^[^\s(]+\(\d+,\d+\): error /.test(line))
  if (!errors.length) {
    print(result)
    done(2, "tsc failed without reporting file errors.")
  }
  const mine = errors.filter(line => files.has(line.slice(0, line.indexOf("("))))
  const elsewhere = errors.length - mine.length
  if (mine.length) {
    console.log(mine.join("\n"))
    done(1, "Type errors in changed files: " + mine.length + "." + (elsewhere ? " " + elsewhere + " more outside the changed files are not counted." : ""))
  }
  done(0, "No type errors in changed files. " + elsewhere + " error(s) outside the changed files are not counted by this gate.")
}

const coverageArgs = (runner, sources, directory) =>
  runner === "jest"
    ? ["--ci", "--silent", "--findRelatedTests", ...sources, "--coverage", "--coverageDirectory=" + directory,
        "--coverageReporters=json-summary", "--coverageReporters=text-summary",
        ...sources.map(path => "--collectCoverageFrom=" + path)]
    : ["related", ...sources, "--run", "--coverage.enabled=true", "--coverage.reportsDirectory=" + directory,
        "--coverage.reporter=json-summary", "--coverage.reporter=text-summary", "--coverage.all=false",
        ...sources.map(path => "--coverage.include=" + path)]

// Runs the tests related to changed source files and requires line coverage per changed file.
const coverage = changed => {
  const sources = changed.filter(path => CODE.test(path) && !TEST.test(path) && !NOT_UNIT_SOURCE.test(path))
  if (!sources.length) done(0, "No changed unit-testable source files; coverage gate not applicable.")
  const runner = has("jest") ? "jest" : has("vitest") ? "vitest" : null
  if (!runner) done(0, "Neither Jest nor Vitest is installed in this project; coverage gate not applicable.")
  if (runner === "vitest" && !["coverage-v8", "coverage-istanbul"].some(name => existsSync(join(root, "node_modules", "@vitest", name))))
    done(0, "Vitest has no coverage provider (@vitest/coverage-v8 or @vitest/coverage-istanbul); coverage gate not applicable.")
  const directory = mkdtempSync(join(tmpdir(), "code-factory-coverage-"))
  try {
    console.log("Running " + runner + " tests related to " + sources.length + " changed source file(s):\n" + sources.join("\n"))
    const result = run(bin(runner), coverageArgs(runner, sources, directory))
    print(result)
    if (result.status !== 0) done(1, "Related tests failed, so coverage was not evaluated.")
    const summaryPath = join(directory, "coverage-summary.json")
    const summary = existsSync(summaryPath) ? JSON.parse(readFileSync(summaryPath, "utf8")) : {}
    // Reports may name files through a symlinked path (/var vs /private/var), so compare real paths.
    const real = path => {
      try {
        return realpathSync(resolve(root, path))
      } catch {
        return resolve(root, path)
      }
    }
    const byFile = new Map(Object.entries(summary).filter(([key]) => key !== "total").map(([key, value]) => [real(key), value]))
    const rows = sources.map(path => ({ path, lines: byFile.get(real(path))?.lines?.pct ?? 0 }))
    for (const row of rows) console.log((row.lines >= THRESHOLD ? "ok  " : "FAIL") + " " + String(row.lines).padStart(6) + "% lines  " + row.path)
    const failing = rows.filter(row => row.lines < THRESHOLD)
    done(failing.length ? 1 : 0, failing.length
      ? failing.length + " changed file(s) below " + THRESHOLD + "% line coverage."
      : "All changed source files have at least " + THRESHOLD + "% line coverage.")
  } finally {
    rmSync(directory, { recursive: true, force: true })
  }
}

const gates = { lint, types, coverage }
const gate = gates[process.argv[2] || ""]
if (!gate) done(2, "Usage: changed-files-gate.mjs <" + Object.keys(gates).join("|") + "> [--base <commit>]")
if (listed === undefined) done(2, "Set CODE_FACTORY_CHANGED_FILES or pass --base <run start commit>.")
gate(listed.split("\n").map(line => line.trim()).filter(Boolean).filter(path => existsSync(join(root, path))))
`;

/** Keep the project's copy of the gate current; a missing or edited copy is rewritten. */
export const ensureChangedFilesGate = async (project: string): Promise<void> => {
  const path = join(project, CHANGED_FILES_GATE_PATH);
  const current = await readFile(path, "utf8").catch(() => null);
  if (current === GATE_SCRIPT) return;
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, GATE_SCRIPT, { mode: 0o644 });
  await rename(temporary, path);
};
